<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>NarcAgent.Plugins</AssemblyName>
    <RootNamespace>NarcAgent.Plugins</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NarcAgent.Core\NarcAgent.Core.csproj" />
  </ItemGroup>

</Project>
